# Generated by Django 3.2.8 on 2021-11-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donor', '0006_auto_20211129_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonor',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A−', 'A−'), ('B+', 'B+'), ('B−', 'B−'), ('AB+', 'AB+'), ('AB−', 'AB−'), ('O+', 'O+'), ('O−', 'O−')], default='A+', max_length=10),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], default='Male', max_length=10),
        ),
    ]
